apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: marketsummary
    context: .
deploy:
  helm:
    releases:
      - name: marketsummary
        chartPath: ./charts/marketsummary
        namespace: springtrader
        values:
          image: marketsummary
        setValueTemplates:
          istio.domain: "{{if .INGRESS_DOMAIN}}{{.INGRESS_DOMAIN}}{{else}}default{{end}}"
